### ISSUE TITLE
global search?

### ISSUE THREAD

**Issue by mojamuto** [sinanislekdemir/poorman#2]
I have a problem that I don't know if it is intentional, when I search for a file, it does not search in all the patches that I have added, I have to select the patch where that file is located and then the search works.
My question is if there is any way to make the search work in all the added patches?

**Comment by sinanislekdemir** [comment]
Hi @mojamuto 

Apologies, I just saw your comment. Hmm that actually makes sense. I will consider that when I've time 👍🏻 I'll keep you posted on this thread.

**Comment by mojamuto** [comment]
Thank you very much for taking it into consideration and for making this program, I had been looking for something like this for a long time.

**Comment by sinanislekdemir** [comment]
Hi @mojamuto 

I guess this should work, let me know if it's buggy or anything. 
I also needed a tool like this and all alternatives were quite old, not working anymore. I wrote this in a very messy way (as the name indicates) without any unit testing😅 It's not my proudest code but it works. 

https://github.com/sinanislekdemir/poorman/releases/tag/v1.0.4

**Comment by mojamuto** [comment]
I haven't had time to try it yet, I'll try it this weekend, thank you very much
